apiVersion: apps/v1
kind: Deployment
metadata:
  name: otus-crud-server-deployment
  labels:
    app: simple-http-crud-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-http-crud-server
  template:
    metadata:
      labels:
        app: simple-http-crud-server
    spec:
      containers:
      - name: simple-http-crud-server
        image: arsenteroganisyan/otus-crud-server:v2
        ports:
        - containerPort: 8000
        env:
          - name: HOST
            valueFrom:
              configMapKeyRef:
                name: config
                key: session_server_host