apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service
  labels:
    app: profile-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-service
  template:
    metadata:
      labels:
        app: profile-service
    spec:
      containers:
      - name: profile-service
        image: arsenteroganisyan/profile-service:v7
        ports:
        - containerPort: 8000
        env:
          - name: SERVER_SESSION_HOST
            valueFrom:
              configMapKeyRef:
                name: config
                key: session_server_host
          - name: CRUD_HOST
            valueFrom:
              configMapKeyRef:
                name: config
                key: crud_host